# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2184b5f0a9f5a020558d095265c949ed7d5fe43079ddc77617059dd2282a6c1a944e88f6a142b482bf7b1d2e91b247e102a14985b76181fed59677d054f3b8c8

test:
  secret_key_base: 06ae5cb04bffd8403741c211dc4b731651087dbe1d0a037e6a75bc279f6eba06fcd62841625163a862957ba8add7969632668035d297d973c849e4ef91ce9e8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
